name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install sbt
        run: |
          curl -L https://github.com/sbt/sbt/releases/download/v1.10.11/sbt-1.10.11.tgz | tar xz
          echo "$PWD/sbt/bin" >> $GITHUB_PATH

      - name: Compile & test
        run: sbt stage


  docker-image:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: kodiak-helped-fawn.ngrok-free.app
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Docker tag
        run: |
          TIMESTAMP=$(date -u +'%Y%m%d%H%M%S')
          export DOCKER_TAG="$TIMESTAMP-${{ github.sha }}"

      - name: Build the Docker image
        run: docker build . --file Dockerfile-packages --target frontend --tag kodiak-helped-fawn.ngrok-free.app/pigbot-frontend:fero-webserver:$DOCKER_TAG

      - name: Push the Docker image
        run: docker push kodiak-helped-fawn.ngrok-free.app/fero-webserver:$DOCKER_TAG