name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install sbt
        run: |
          curl -L https://github.com/sbt/sbt/releases/download/v1.10.11/sbt-1.10.11.tgz | tar xz
          echo "$PWD/sbt/bin" >> $GITHUB_PATH

      - name: Compile & test
        run: sbt stage

  docker-image:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    container:
      image: gcr.io/kaniko-project/executor:v1.23.2-debug
      options: --entrypoint=""
      env:
        DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG }}
    steps:
      - name: Build and push Docker image
        run: |
          echo "$DOCKER_AUTH_CONFIG" > /kaniko/.docker/config.json
          TIMESTAMP=$(date -u +'%Y%m%d%H%M%S')
          DOCKER_TAG="$TIMESTAMP-${{ github.sha }}"
          /kaniko/executor --context . --dockerfile Dockerfile --destination kodiak-helped-fawn.ngrok-free.app/fero-webserver:$DOCKER_TAG